export const ERROR_CODES = {
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  BAD_PAYLOAD: 'BAD_PAYLOAD',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EXISTS: 'USER_EXISTS',
  PASSWORD_NOT_SET: 'PASSWORD_NOT_SET',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
} as const;
